app/ToDo/models.py
# import all the necessary library


from app import db
from datetime import date, datetime

# create company databse model


class ToDos(db.Model):
    __tablename__ = 'todo'
    id = db.Column(db.Integer, primary_key=True)
    todo_name = db.Column(db.String(50), unique=True, nullable=False)
    todo_description = db.Column(db.String(50))
    todo_created_date = db.Column(db.DateTime)
    todo_status = db.Column(db.String(50), nullable=False)

    def __init__(self,todo_name,todo_description,todo_created_date,todo_status):

        self.todo_name = todo_name
        self.todo_description = todo_description
        self.todo_created_date = todo_created_date
        self.todo_status = todo_status

    def __reper__(self):
        return 'The name is {}'.format(self.todo_name)

app/ToDo/forms.py
# import all the necessary library


from wtforms.fields.core import DateField, IntegerField, SelectField
from app.ToDo.models import ToDos
from flask_wtf import FlaskForm, form
from wtforms import StringField, TextField, SubmitField, PasswordField, BooleanField,validators
from wtforms.validators import DataRequired, InputRequired, Length, Email, EqualTo, URL, ValidationError,Optional,Regexp
from datetime import datetime, date

#  create todo form


class CreateToDo(FlaskForm):
    today = date.today()
    todo_name = StringField('ToDo Name', render_kw={'autofocus': True}, validators=[DataRequired()])
    todo_description = StringField('ToDo Description',validators=[DataRequired()])
    todo_created_date = DateField('ToDo Created Date',default=today,validators=[DataRequired()])
    todo_status = SelectField('Status Type',choices=['','NotStarted','OnGoing','Completed'],validators=[DataRequired()])

 # edit todo form


class EditToDoForm(FlaskForm):
    todo_name = StringField('ToDo Name', render_kw={'autofocus': True}, validators=[DataRequired()])
    todo_description = StringField('ToDo Description', validators=[DataRequired()])
    todo_created_date = DateField('ToDo Created Date', validators=[DataRequired()])
    todo_status = SelectField('Status Type', choices=['', 'NotStarted', 'OnGoing', 'Completed'],validators=[DataRequired()])
    submit = SubmitField('Update')

    

app/ToDo/__init__.py
#  create blueprint 

# app/companyinfo/__init__.py

from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from app.ToDo import routes

app/ToDo/routes.py
# import all the necessary library

from app.ToDo import main
from app import db
from app.ToDo.models import ToDos
from app.ToDo.forms import CreateToDo,EditToDoForm
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required


# company list display
@main.route('/todolist')
@login_required
def display_todo_name():
    todo_names = ToDos.query.all()
    return render_template('todo_list.html', todo_names=todo_names)

# home page display


@main.route('/dashboard')
@login_required
def display_dashboard():
    return render_template('home.html')

# route company create form
@main.route('/createtodo', methods=['GET','POST'])
@login_required
def create_todo():
    form = CreateToDo()
    
    if form.validate_on_submit():
        todo_info = ToDos(

            todo_name=form.todo_name.data,
            todo_status=form.todo_status.data,
            todo_description=form.todo_description.data,
            todo_created_date=form.todo_created_date.data)

        db.session.add(todo_info)
        db.session.commit()
        flash('Record save Sucessfuly')
        return redirect(url_for('main.create_todo'))

    return render_template('create_todo.html', form=form)
        

#  route edit company data form

@main.route('/edit/todo/<todo_id>', methods=['GET', 'POST'])
@login_required
def edit_todo(todo_id):
    todos = ToDos.query.get(todo_id)

    form = EditToDoForm(obj=todos)
    form.todo_status.choices = [todos.todo_status,'','NotStarted','OnGoing','Completed']
    if form.validate_on_submit():
        todos.todo_name = form.todo_name.data,
        todos.todo_status = form.todo_status.data,
        todos.todo_description = form.todo_description.data,
        todos.todo_created_date = form.todo_created_date.data,
        db.session.add(todos)
        db.session.commit()
        flash('Task Edited Successfully')
        return redirect(url_for('main.display_todo_name'))
    return render_template('edit_todo.html',form=form, todos=todos)
#

# route delete company data form

@main.route('/delete/todo/<todo_id>', methods=['GET', 'POST'])
@login_required
def delete_todo(todo_id):
    todos = ToDos.query.get(todo_id)
    if request.method == 'POST':
        db.session.delete(todos)
        db.session.commit()
        flash('Task deleted Sucessfully')
        return redirect(url_for('main.display_todo_name'))
    return render_template('delete_todo.html', todos=todos, todo_id=todo_id)


# route error handling

@main.app_errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

app/ToDo/templates/create_todo.html
{% extends 'layout.html' %}
<!-- {% import "bootstrap/wtf.html" as wtf %} -->

{% block content %}
<h1 class="company_header">CREATE TODO</h1>
<hr>

<div id="company_container" class="container">

    <form method="POST" name="createCompany" id="createForm" action="{{ url_for('main.create_todo') }}">
        {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.todo_name.label(class="form-control-label") }}
                
                {{ form.todo_name(class="form-control") }}

                {% for error in form.todo_name.errors %}

                <span style="color:red;">
                    {{error}}

                </span>
                {% endfor %}
                
            </div>
            <div class="form-group">
                {{ form.todo_status.label(class="form-control-label") }}
                {{ form.todo_status(class="form-control") }}

            </div>  
            
            <div class="form-group">
                {{ form.todo_description.label(class="form-control-label") }}
                {{ form.todo_description(class="form-control") }}
                
            </div>
            <div class="form-group">
                {{ form.todo_created_date.label(class="form-control-label") }}
                {{ form.todo_created_date(class="form-control") }}
            </div>

            <div class="btnoutline" id="btnoutline">
                <button type="submit" class="btn btn-success">Save</button>
                <button type="submit" id="buttonCancel" class="btn btn-info">
                    <a href="{{url_for('main.create_todo')}}" style="color: rgb(243, 239, 239)">Cancel</a>
                
                </button>
                
                <hr>
    
            </div>

        <hr>
                
    </form>   
</div>
<hr>

{% endblock %}

app/ToDo/templates/delete_todo.html
{% extends 'layout.html' %}


    {% block content %}

    <div id="idContainerDeleteCompany" class="container-fluid">
          

        <br>
            <h2 class="company_name_heading">TASK DETAILS</h2>
        <br>
            
            <div class="table table-bordered">
              
              <table class="table">
                <thead class="">
                  <tr>
                     <th scope="col">ID</th>
                    <th scope="col">TODO NAME</th>
                    <th scope="col">TODO DESCRIPTION</th>
                    <th scope="col">TODO DATE</th>
                    <th scope="col">TODO STATUS</th>
                    <th id="edit_header" scope="col"> DELETE </th>
                    <th id="delete_header" scope="col"> CANCEL </th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{todos.id}}</td>
                        <td>{{todos.todo_name}}</td>
                        <td>{{todos.todo_description}}</td>
                        <td>{{todos.todo_created_date}}</td>
                        <td>{{todos.todo_status}}</td>
                        
                        <td>
                            
                           <form action="" method="POST" onclick="return confirm('Are you sure you want to delete this item?');">
                               <button type="submit" id="" class="btn btn-sm btn-danger">DELETE</button>
                               
                           </form>
                           
                        <td> 
                        
                        <button type="submit" id="idButtonCancel" class="btn btn-sm btn-primary">
                            <a href="{{ url_for('main.display_todo_name')}}" style="color: rgb(243, 239, 239)">CANCEL</a>
                        </button>
                        
                      </tr>
                </tbody>
                  
              </table>
            
            </div>
            
            
            </div>


       
{% endblock %}

app/ToDo/templates/edit_todo.html
{% extends 'layout.html' %}
<!-- {% import "bootstrap/wtf.html" as wtf %} -->

{% block content %}


<h1 class="company_header">EDIT TODO</h1>
<hr>
<div id="company_edit_container" class="container">

    <form method="POST" name="editCompany" id="editForm" action="">
        {{ form.hidden_tag() }}
    
            <div class="form-group">
               
                {{ form.todo_name.label(class="form-control-label") }}
                
                {{ form.todo_name(class="form-control")}}

                {% for error in form.todo_name.errors %}

                <span style="color:red;">
                    {{error}}

                </span>
                {% endfor %}
                
            </div>
            <div class="form-group">
                {{ form.todo_status.label(class="form-control-label") }}
                {{ form.todo_status(class="form-control") }}

            </div>  
            
            <div class="form-group">
                {{ form.todo_description.label(class="form-control-label") }}
                {{ form.todo_description(class="form-control") }}
                
            </div>
            <div tabindex="=3" class="form-group">
                {{ form.todo_created_date.label(class="form-control-label") }}
                {{ form.todo_created_date(class="form-control") }}
            </div>

            <div class="btnoutline" >
                <button type="submit" class="btn btn-success" onclick="return confirm('Are you sure you want to save this item?');">Save</button>
                <button type="submit" id="buttonCancel" class="btn btn-info">
                    <a href="{{url_for('main.display_dashboard')}}" style="color: rgb(243, 239, 239)">Cancel</a>
                
                </button>
                
                <hr>
    
            </div>

        <hr>
                
    </form>   
</div>
<hr>

<!-- <div id="company_container" class="container">
   

    {{ form.hidden_tag() }}
    {{ wtf.quick_form(form) }}

    
</div>

<hr> -->
{% endblock %}

app/ToDo/templates/home.html
{% extends 'layout.html' %}


    {% block content %}


    
{% endblock %}

app/ToDo/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        
        <title>TO DO PROJECT</title>

        <!-- Latest compiled and minified CSS -->
       
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Sansita&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/todoname.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/create_todo.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/tododelete.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/msgBox.css') }}">

        <script src="{{ url_for('static', filename='js/hamburgmenu.js') }}"></script>
        <script src="{{ url_for('static', filename='js/delconmessage.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/msgBox.js') }}"></script>

        
      
    </head>

    {% block body %}

    <div class="wrapper">
<!--        flash messages-->
<!--        {% for message in get_flashed_messages()%}-->

<!--        <div id="messageDisplay" class="container alert alert-info">-->
<!--            <button type="button" class="close" data-dismiss="alert" onclick=delete_flash()>&times;</button>-->
<!--            {{ message }}-->

<!--        </div>-->
<!--        {% endfor %}-->

    <body>

            {# navigation bar #}
            {% block navbar %}
            <div class="topnav" id="myTopnav">

                <a class="active" href="{{ url_for('main.display_dashboard') }}">TO DO PROJECT</a>
                
                <div class="socialmedia">

<!--                    <a href="{{ url_for('authentication.signup') }}"><i class="fa fa-registered"></i> SignUp </a>-->
                    {% if current_user.is_authenticated %}

                        <a href="{{ url_for('authentication.log_out_user')}}"><i class="fa fa-sign-in"></i> Sign Out </a>
                    {% else %} 
                        <a href="{{ url_for('authentication.do_the_login')}}"><i class="fa fa-registered"></i> Sign In </a>
                    {% endif %}

                    <a href="">
                        {%  if current_user.is_authenticated %}
                            LoggedIn as <b style="color: deeppink">{{ current_user.user_name.title() }}</b>
                        {% else %}
                            Not LoggedIn
                        {% endif %}
                    </a>


                </div>
                

                <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </a>
                
              </div>
             
            {% endblock navbar %}

            {% block sidebar %}
            <!-- The sidebar -->
                <div class="sidebar">
                    <a href="{{ url_for('main.display_todo_name')}}"><i></i> To Do List </a>
                    <a href="{{ url_for('main.create_todo')}}">Create To Do</a>

                    
                </div>
            {% endblock sidebar %}

            
    
            {# empty block for custom content #}
            {% block content %} {% endblock content %}

            

    
            {# footer #}
            {% block footer %}
            <footer>
                <div id="footer">
                    <hr>
                    <p class="text-center small"> To Do Project &copy;	| 2022 </p>
                    <hr>
                </div>
            </footer>
            {% endblock footer %}
    
        </div>
        
    </body>
    {% endblock body %}
    

</html>

app/ToDo/templates/todo_list.html
{% extends 'layout.html' %}


    {% block content %}
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}"> -->

        <div id="" class="container-fluid">
          <br>

            <h2 class="company_name_heading">TO DO LIST</h2>
          <br>
            
            <div class="table table-bordered">
              
              <table class="table">
                <thead class="">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">TODO NAME</th>
                    <th scope="col">TODO DESCRIPTION</th>
                    <th scope="col">TODO DATE</th>
                    <th scope="col">TODO STATUS</th>
                    <th id="edit_header" scope="col">EDIT</th>
                    <th id="delete_header" scope="col">DELETE</th>
                  </tr>
                </thead>
                <tbody>
                    {% for todos in todo_names %}
                       <tr>
                         <td>{{todos.id}}</td>
                         <td>{{todos.todo_name}}</td>
                         <td>{{todos.todo_description}}</td>
                         <td>{{todos.todo_created_date}}</td>
                         <td>{{todos.todo_status}}</td>
                         <td>
                           <button class="btn btn-sm btn-primary" id="idDeleteButton">
                               <a href="{{ url_for('main.edit_todo',todo_id=todos.id) }}" style="color: rgb(237, 245, 239)">EDIT</a>



                           </button>

                          
                         </td>
                         
                         <td>
                      
                           <button class="btn btn-sm btn-danger" id="idCancelButton">
                               <a href="{{ url_for('main.delete_todo', todo_id=todos.id) }}" style="color: rgb(243, 239, 239)">DELETE</a>

                          </button>
                          </td>
                       </tr>
                     {% endfor %}
               </tbody>
            
              </table>
            
            </div>
            
            
            </div>
        
      
{% endblock %}